from acoustic_whale import gallant_yonath as gallant_yonath1
from acoustic_whale import tender_rosalind as tender_rosalind1
from priceless_stonebraker.quizzical_hamilton.ecstatic_hoover import pedantic_noyce as pedantic_noyce1
from acoustic_whale import focused_liskov as focused_liskov1
