from elegant_tesla.boring_dijkstra.agitated_goldberg import quirky_cori as quirky_cori1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
from peaceful_bohr.zen_pike.agitated_goldberg import pedantic_hugle as pedantic_hugle1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
