from acoustic_whale import gracious_kare as gracious_kare1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
from acoustic_whale import lucid_jackson as lucid_jackson1
from peaceful_bohr.wizardly_jepsen import focused_mirzakhani as focused_mirzakhani1
