from acoustic_whale import determined_wing as determined_wing1
from elegant_tesla.zen_pike import hopeful_ritchie as hopeful_ritchie1
from acoustic_whale import condescending_franklin as condescending_franklin1
