from acoustic_whale import loving_jepsen as loving_jepsen1
from stupefied_gates import infallible_banach as infallible_banach1
from elegant_tesla.reverent_goldwasser.eloquent_borg import eloquent_borg as eloquent_borg1
from acoustic_whale import cranky_swanson as cranky_swanson1
from acoustic_whale import gracious_kare as gracious_kare1
from stupefied_gates import jovial_benz as jovial_benz1
