from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan import blissful_spence as blissful_spence1
from elegant_tesla.reverent_nightingale.vigorous_stallman.cranky_ramanujan import zen_curie as zen_curie1
from acoustic_whale import suspicious_goldstine as suspicious_goldstine1
from acoustic_whale import unruffled_yonath as unruffled_yonath1
