from acoustic_whale import peaceful_turing as peaceful_turing1
from acoustic_whale import keen_mclean as keen_mclean1
from peaceful_bohr.zen_pike.eager_swanson import wonderful_kare as wonderful_kare1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
