from elegant_tesla.boring_dijkstra import friendly_hodgkin as friendly_hodgkin1
from elegant_tesla.boring_boyd import gracious_bassi as gracious_bassi1
from acoustic_whale import objective_meitner as objective_meitner1
from elegant_tesla.boring_dijkstra import zen_pike as zen_pike1
from acoustic_whale import cocky_pike as cocky_pike1
