from elegant_tesla.zen_pike.cranky_tesla import gifted_yonath as gifted_yonath1
from acoustic_whale import sleepy_shannon as sleepy_shannon1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
