from acoustic_whale import naughty_nightingale as naughty_nightingale1
from acoustic_whale import nostalgic_wilson as nostalgic_wilson1
from acoustic_whale import angry_dijkstra as angry_dijkstra1
from acoustic_whale import unruffled_shannon as unruffled_shannon1
from elegant_tesla.boring_boyd import affectionate_pike as affectionate_pike1
from elegant_tesla.zen_pike.optimistic_hawking.elated_darwin import suspicious_meitner as suspicious_meitner1
