from elegant_tesla.boring_boyd import zen_curie as zen_curie1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
