from elegant_tesla.cranky_goldwasser import quirky_bartik as quirky_bartik1
from acoustic_whale import reverent_fermi as reverent_fermi1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
from peaceful_bohr.eloquent_liskov import focused_mirzakhani as focused_mirzakhani1
