from elegant_tesla.zen_pike import pedantic_lichterman as pedantic_lichterman1
from acoustic_whale import amazing_shirley as amazing_shirley1
from acoustic_whale import cranky_swanson as cranky_swanson1
