from elegant_tesla.cranky_goldwasser.awesome_noyce import stoic_pike as stoic_pike1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
from acoustic_whale import unruffled_yonath as unruffled_yonath1
