from loving_visvesvaraya.confident_hoover.relaxed_spence import musing_fermi as musing_fermi1
from acoustic_whale import objective_mahavira as objective_mahavira1
from loving_visvesvaraya.confident_hoover.peaceful_bohr import nostalgic_lovelace as nostalgic_lovelace1
from acoustic_whale import vigorous_thompson as vigorous_thompson1
