from modest_stonebraker.hopeful_carson import clever_brown as clever_brown1
from acoustic_whale import hungry_neumann as hungry_neumann1
from modest_stonebraker.hopeful_carson import epic_wiles as epic_wiles1
from acoustic_whale import hopeful_northcutt as hopeful_northcutt1
